services:
  # Django service (Web server)
  web:
    build: .
    container_name: django_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    depends_on:
      - redis
    networks:
      - backend

  # Celery Worker service
  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A setup worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - backend

  # Celery Beat service
  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A setup beat --loglevel=info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - backend

  # Redis service (Celery broker)
  redis:
    image: "redis:latest"
    container_name: redis
    networks:
      - backend

networks:
  backend:
    driver: bridge

